# Generated by Django 5.2.6 on 2025-10-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('prioridad', models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=3, verbose_name='Prioridad')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_limite', models.DateField(blank=True, null=True, verbose_name='Fecha límite')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
